server:
  port: 8084
spring:
  profiles:
    active: prod
  application:
    name: ems

  datasource:
    url: jdbc:mysql://localhost:3306/MARCH2024
    username: root
    password: password

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

city: Fairfax